### ISSUE TITLE
Monitor "log-alert" setting up warning threshold = 1 even if not defined

### ISSUE THREAD

**Issue by flavio-cadete-cko** [DataDog/terraform-provider-datadog#1045]
As the title says it, on log-alert, datadog is setting up warning_threshold = 1 as default if no critical_threshold is defined (should pick up from the query)
This doesn't occurs on query-alert monitors.

**Comment by zippolyte** [comment]
Correct me if I'm wrong, but this only appears like so in the UI, when you try to edit the monitor that was created via terraform right ? There the `warning threshold` input will have a 1. But as long as you don't click save in that UI, the monitor doesn't have a warning threshold set, i.e. terraform doesn't generate a new plan after the first apply.

If I'm correct, this isn't a terraform issue but rather something to do with our UI. Could you try to open a ticket with support so that it properly tracked by the team in charge ? Feel free to link this issue for context.

**Comment by flavio-cadete-cko** [comment]
yeah, on terraform plan/apply doesn't show warning = 1, but on UI yeah. 
Can you point me where I should create the ticket?

**Comment by zippolyte** [comment]
This page has the information on how to contact support https://www.datadoghq.com/support/
