### ISSUE TITLE
Terraform Datadog Dashboard - query_table_definition widget Issue 

### ISSUE THREAD

**Issue by Yokeni** [DataDog/terraform-provider-datadog#1063]
Hi Team,
We have Terraform integration with Datadog and are seeing an issue when we execute the terraform plan for creating the Dashboard in Datadog. It seems terraform does not support some field which are supported by Datadog.

Issue:
In Datadog when we create a Dashboard with query_table_definition widget type and import the json file we do see the  fields apm_stats_query -> columns in it. However in terraform file if we include these fields we get an error when we run terraform plan command.
As mentioned in Datadog site the given field are supported (refer Model section)
https://docs.datadoghq.com/dashboards/widgets/table/

Datadog json details example shows the field apm_stats_query and the columns field under it.
"requests": [
    {
      "aggregator": "string",
      "alias": "string",
      "apm_query": {
        "compute": {
          "aggregation": "avg",
          "facet": "@duration",
          "interval": 5000
        },
        "group_by": [
          {
            "facet": "resource_name",
            "limit": 50,
            "sort": {
              "aggregation": "avg",
              "facet": "@string_query.interval",
              "order": "desc"
            }
          }
        ],
        "index": "days-3,days-7",
        "multi_compute": [
          {
            "aggregation": "avg",
            "facet": "@duration",
            "interval": 5000
          }
        ],
        "search": {
          "query": ""
        }
      },
      "apm_stats_query": {
        "columns": [
          {
            "alias": "Requests",
            "cell_display_mode": "number",
            "name": "Reqs",
            "order": "desc"
          },
          {
            "alias": "Requests_new",
            "cell_display_mode": "number",
            "name": "Reqs_new",
            "order": "desc"
          }
        ],
        "env": "prod",
        "name": "rack.request",
        "primary_tag": "datacenter:*",
        "resource": "CartsController",
        "row_type": "service",
        "service": "web-store"
      }
However in terraform dashboard page under "query_table_definition" widget section, we do not see these fields:
https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard

Example of query_table_definition widget on terraform site:
widget {
    query_table_definition {
      request {
        q          = "avg:system.load.1{env:staging} by {account}"
        aggregator = "sum"
        limit      = "10"
        conditional_formats {
          comparator = "<"
          value      = "2"
          palette    = "white_on_green"
        }
        conditional_formats {
          comparator = ">"
          value      = "2.2"
          palette    = "white_on_red"
        }
      }
      title     = "Widget Title"
      live_span = "1h"
    }
  }

Source/Version used in the terraform plan:
source = "Datadog/datadog"
version = ">= 0.14.9"

As the fields are supported by Datadog, we expect it to be supported in terraform also. Can you please look into this issue.

Regards,
Yogesh

**Comment by zippolyte** [comment]
Hey @Yokeni 

This field is supported by the provider. You can see documentation for it here https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard#nestedblock--widget--query_table_definition--request--apm_stats_query (don't mind the title that says it's for `security_query`, its a bug in how the documentation is generated and will be fixed when the next provider version is shipped).

It's not in the example because we just can't create an example for every single field, the dashboard example is already pretty big.

If you're having an error you would like us to investigate, please give us your terraform configuration for this dashboard that errors out, the version of the Datadog provider you are using (`terraform version` command should give that), as well as a copy of the exact error you are having from the terraform output.

Thanks
