### ISSUE TITLE
Feature Request: Apply and Destroy events

### ISSUE THREAD

**Issue by Indigenuity** [DataDog/terraform-provider-datadog#1261]
### Proposed Feature
Send an Event from the Datadog provider when `terraform apply` or `terraform destroy` are run.  

### Why
Datadog [Events](https://docs.datadoghq.com/events/) are useful for monitoring deploys and CI/CD actions. "Why did my web service just change behavior? Oh, someone ran `apply` 30 seconds before the behavior change".

Other IaC tools like Ansible have [ways to send events to datadog](https://docs.ansible.com/ansible/latest/collections/community/general/datadog_event_module.html) when they are run.  

### Proposed configuration

Since events are not really resources in the traditional Terraform sense, this would likely be part of the provider configuration itself.  

```
terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
      events = {
        enabled = true
        tags = {
          "service": "foo"
          "env": "dev"
        }
        aggregation_key = "bar"
        # .. and so on with other config values in the Events API
      }
    }
  }
}
```
For all `apply` and `destroy` commands carried out by this provider, an Event would be sent to datadog with the appropriate tags, etc.

Alternatively, there could be a resource type that always has changes when resources in its `depends_on` are modified by an `apply` or `destroy`

**Comment by MrTrustworthy** [comment]
Is it possible to re-open this issue?

I've read the updated docs mentioned in [the linked MR](https://github.com/DataDog/integrations-core/pull/11475), but this does not fully address this issue.

In places like standardised CI setups, I can already send DataDog events automatically by simply configuring in the CI to curl a DataDog events endpoint after running `terraform apply`. The `dogwrap` approach references in the MR is slightly nicer, since it automatically takes care of some things. 

However, it's not solving the issue of "I want to have DataDog events whenever I run `terraform apply`". 

The difference is that the dogwrap command has to be explicitly configured in all places where `terraform apply` would be run. While this is doable in CI (even though there will surely be some places where it's forgotten...), it's not practical for manually triggered terraform runs. It also doesn't automatically use the DataDog provider credentials, which might themselves come from ex. Hashicorp Vault, which would make the wrapper command even more complex in practice.

The user story here would be "When I run `terraform apply`, I want an event with the terraform changes to be pushed into DataDog, so I can reliably see all manual or automatic deploys of Terraform"

**Comment by therve** [comment]
We investigated this, and as far as we know there is no way in a Terraform provider to subscribe to lifecycle events which would match the whole apply. We can create events per resource, but it would be incredibly noisy on any non-trivial stack. That's how we settled for dogwrap for now, but if you have any suggestion we're happy to hear it.

**Comment by MrTrustworthy** [comment]
Thanks for the response :) 

I'm not too familiar with TF Provider development, and browsing the docs I also couldn't find a lifecycle hook to achieve that.

My only idea for a workaround would be: Have a "datadog_event" resource that (1) sends a "plan" event when refreshing its state and/or (2) that always shows a diff and will create an "apply" event when updating it.

Either/both are not ideal and come with their own limitations and concessions. Though, maybe there's some ways to mitigate them, so that they are at least usable for some simple use cases like "just track every TF apply".
