### ISSUE TITLE
v3.11.0, v3.3.0, cannot import shared dashboard 8jr-syt-6fn

### ISSUE THREAD

**Issue by bjd2385** [DataDog/terraform-provider-datadog#1424]
### Terraform Version

```
❯ terraform version
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/datadog/datadog v3.11.0

Your version of Terraform is out of date! The latest version
is 1.1.9. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

-   `datadog_dashboard`

### Terraform Configuration Files

N/A

### Debug Output

Same as below **Actual Behavior** when running
```
❯ TFLOG=debug terraform import datadog_dashboard.dashboard 8jr-syt-6fn
```

### Panic Output

N/A

### Expected Behavior

The dashboard should have been imported successfully to tfstate.

### Actual Behavior

```
terraform import datadog_dashboard.dashboard 8jr-syt-6fn
datadog_dashboard.dashboard: Importing from ID "8jr-syt-6fn"...
datadog_dashboard.dashboard: Import prepared!
  Prepared datadog_dashboard for import
datadog_dashboard.dashboard: Refreshing state... [id=8jr-syt-6fn]
╷
│ Error: object contains unparsed element: map[definition:map[legend_columns:[avg min max value sum] legend_layout:auto markers:[] requests:[map[display_type:line log_query:map[compute:map[aggregation:count] group_by:[map[facet:@context.adapter.vertical limit:50 sort:map[aggregation:count order:desc]]] index:main search:map[query:kube_namespace:production -service:users-service -@tags.url:("/api/healthcheck" OR "/") -@tags.type:"outbound request" $vertical $adapter $building $brand $region $version $user-uuid]] style:map[line_type:solid line_width:normal palette:dog_classic]]] show_legend:true title:Log count by Vertical title_align:left title_size:16 type:timeseries yaxis:map[include_zero:true label: max:auto min:auto scale:linear]] id:4.237249104850998e+15 layout:map[height:26 width:54 x:0 y:0.06997492283950617]]
│
│
╵
```

### Steps to Reproduce

Run `terraform import`, as in the CLI output above.

### Important Factoids

N/A

### References

N/A

**Comment by bjd2385** [comment]
Just to update, tried a bunch of terraform versions from 1.1.7 down to 1.0.1, as well as dd provider versions back to the latest 2.x.x, and this issue seems to plague almost all v3 providers.

**Comment by skarimo** [comment]
Hi, could you share the json output of the dashboard. Thank!

**Comment by bjd2385** [comment]
Sure! Sorry it's been a while since I last replied here - 

https://gist.github.com/bjd2385/57cd9ce1aad25e7a23a29bef48ccf7e4

I've added it to Gist as GH seemingly doesn't allow you to upload JSON files.

**Comment by skarimo** [comment]
@bjd2385 Thanks for forwarding that. This was an issue with the dashboard where the `x`, and `y` layout property of the widget was stored as floats instead of the expected integer type. To fix this, simply resize the `Error Log count by Adapter` widget and save the dashboard. This should reset the layout property to correct values. Thanks!

**Comment by seanturner026** [comment]
Running into the same issue.

Getting the following error when I try and import:

`Error: object contains unparsed element: map[comparator:= palette:white_on_green value:1]`

Needed to remove the query value widgets one by one in order to be able to import. Worth mentioning that the `white_on_green value:1` would change as the widgets were iterated through (e.g. it was a 6 at one point).

https://gist.github.com/seanturner026/0ba1b8d69c644cf6d74d65534075e531
