### ISSUE TITLE
Synthetics: follow_redirects  is not available for configuration in the HTTP test's request_definition

### ISSUE THREAD

**Issue by tamas-hoffman** [DataDog/terraform-provider-datadog#1631]
## Terraform Version
terraform v3.17.0

## Affected Resource(s)
Please list the resources as a list, for example:

[datadog_synthetics_test](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test)

## Terraform Configuration Files
```hcl
resource "datadog_synthetics_test" "test_api" {
  type    = "api"
  subtype = "http"

  request_definition {
    method    = "GET"
    url       = "https://google.com"
    follow_redirects = true    # <- this is not supported by provider

  }
```

## References
Datadog console allows you to enable redirects following in an HTTP test's request definition.

Latest version of terraform provider does not support this.

**Comment by nkzou** [comment]
Hi there, the `follow_redirects` option for non-multistep synthetic tests is defined in the `options_list` field, instead of `request_definition`. For example:
```terraform
resource "datadog_synthetics_test" "test_api" {
  type    = "api"
  subtype = "http"
  request_definition {
    method = "GET"
    url    = "https://www.example.org"
  }
  options_list {
    tick_every = 900
    follow_redirects = true
  }
  ...
}
```
Note that for multi-step synthetics tests, the `follow_redirects` option is found in the `request_definition` for each step.
Hopefully this solves your issue - if not feel free to reopen the issue with more details.
