### ISSUE TITLE
datadog_integration_pagerduty_service_object missing import

### ISSUE THREAD

**Issue by tmidi** [DataDog/terraform-provider-datadog#1822]
Hi There,
Both `datadog_integration_pagerduty` and `datadog_integration_pagerduty_service_object` don't have import functions.

### Terraform Version

`all versions`

### Affected Resource(s)

-   `datadog_integration_pagerduty_service_object`
-   `datadog_integration_pagerduty`

### Expected Behavior

Both resources should have an import function.

**Comment by therve** [comment]
For security reasons the service key is not returned by the API, so it's impossible to import those. Sorry for the inconvenience.

**Comment by fernandobarroso-signifyd** [comment]
Hi @therve ,
I need the import for this resource not for getting the service key, but just for Terraform knowing that it already exists. Otherwise, it tries to create it again, resulting in this error: `Error: error creating PagerDuty integration service from https://app.datadoghq.com/api/v1/integration/pagerduty/configuration/services: 400 Bad Request: {"errors":["Service already exists"]}`.
Is there a way to prevent this?

**Comment by skyzyx** [comment]
Same issue. We need to be able to import state somehow.

**Comment by ruben-chainalysis** [comment]
I also hit this, [here's a PR I pushed to solve the issue](https://github.com/DataDog/terraform-provider-datadog/pull/2286) (it works for me now, but feel free to add any comments if there's any other thing I missed).
