### ISSUE TITLE
terraform apply with datadog_integration_aws resource resets collected metrics from AWS services

### ISSUE THREAD

**Issue by vilhomaa** [DataDog/terraform-provider-datadog#1895]
After running terraform apply, all metrics being collected in DataDog get reset to the metrics collected by default. 
Not sure if this is intended behaviour. if not, then being able to specify what metrics are to be collected from what AWS services would be nice to have. Currently, if someone in the organisation runs terraform apply with the datadog_integration_aws resource, and doesn't remember to go manually enable all the metrics being collected, e.g. all cost metric monitoring from AWS gets disabled. 

### Terraform Version

terraform v1.4.6

### Affected Resource(s)

-  datadog_integration_aws
- metrics being collected from AWS services

### Terraform Configuration Files

```hcl
resource "datadog_integration_aws" "sandbox" {
  account_id                       = var.account_id 
  role_name                        = "DatadogAWSIntegrationRole"
  host_tags                        = ["REDACTED"]
  metrics_collection_enabled = "true"
}
```

### Expected Behavior

After terraform apply, the metrics being collected, as visible in the metrics tab under the AWS integration in datadog GUI, stay enabled:
![image](https://user-images.githubusercontent.com/34384871/235175160-c2de01e0-14f7-447a-aaee-790ceef30b50.png)

### Actual Behavior

After terraform apply, the metrics being collected reset to the default ones:
![image](https://user-images.githubusercontent.com/34384871/235175331-a10f39ad-2fa6-4934-b5fa-c4f4fc5f62e7.png)

### Steps to Reproduce

1. set up AWS integration with datadog_integration_aws resource, run terraform apply
2. Enable collection of all metrics in DataDog GUI under integrations/aws/account
3. run terraform plan & apply
4. observe that the chosen metrics to be collected has been reset

**Comment by robertbozsik** [comment]
Would be also great to have an option either to click and save "Enable All" or select each desired metrics from Terraform directly instead of using the DataDog UI every time.

**Comment by nkzou** [comment]
What's happening here is expected behavior - if you set up the integration with terraform, then change the resource outside of terraform (via the UI in this case), terraform will (and should) overwrite any changes it detects with its own config, as the terraform config files are considered the source of truth.

In your case, you need to add the metrics you're interested in collecting to the [`account_specific_namespace_rules`](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_aws#account_specific_namespace_rules) field.

For example,
```
resource "datadog_integration_aws" "sandbox" {
  account_id  = "1234567890"
  role_name   = "DatadogAWSIntegrationRole"
  filter_tags = ["key:value"]
  host_tags   = ["key:value", "key2:value2"]
  account_specific_namespace_rules = {
    auto_scaling = false
    opsworks     = false
  }
}
```
Where `account_specific_namespace_rules` is a map of strings to booleans defining collection behavior for each metric. You can retrieve a list of available namespace rules from [the API docs](https://docs.datadoghq.com/api/latest/aws-integration/#list-namespace-rules), also linked from the terraform provider docs for the AWS integration.

Hopefully this helps, and make sure to reach out if there's any confusion still.
