### ISSUE TITLE
Add restricted_roles property to datadog_dashboard_json resource

### ISSUE THREAD

**Issue by rclark** [DataDog/terraform-provider-datadog#1960]
The datadog_dashboard_json resource type is extremely convenient, allowing me to prototype dashboard changes in the UI, and easily export JSON and place those changes under terraform's control.

But the resource type lacks many of the other "meta" properties that the datadog_dashboard resource is capable of capturing. In particular, [I would like to be able to set `restricted_roles`](https://docs.datadoghq.com/dashboards/guide/how-to-use-terraform-to-restrict-dashboard-edit/) on a dashboard that I've defined, as JSON, in terraform.

### Terraform Version

N/A

### Affected Resource(s)

-   datadog_dashboard_json

### Terraform Configuration Files

```hcl
resource "datadog_dashboard_json" "json" {
  dashboard = file("${path.module}/dashboard.json")
}
```

### Expected Behavior

```hcl
resource "datadog_dashboard_json" "json" {
  dashboard = file("${path.module}/dashboard.json")
  restricted_roles = ["xxx"]
}

**Comment by skarimo** [comment]
For the purpose of json resources, extrapolating attributes would complicate things a bit and defeat the purpose. Ultimately, we would end up with a copy of the dashboard resource itself.

For your use case, you should be able to use terraform functions. For example:
```
resource "datadog_dashboard_json" "json" {
  dashboard = jsonencode(
      merge(
         jsondecode(file("${path.module}/dashboard.json")), 
         {"restricted_roles": ["xxx"]}
      )
   )
}
```
Let me know if this works for your use case

**Comment by rclark** [comment]
Yes, it does appear that adding `"restricted_roles"` to the JSON resource has the intended effect on the dashboard. But I'll just call out a few things that look like related bugs to me, here and in other DataDog spaces:

1. When you export from a dashboard that's been configured in the UI, the `"restricted_roles"` property is not included in the JSON.
2. If you create a dashboard using the `dashboard_json` resource with no permissions, then in the UI add role-based write controls, then `terraform plan` again -- your plan indicates that it is going to correct that "drift" by removing the `"is_read_only"` attribute, while I would have expected it to say it would remove the `"restricted_roles"` attribute.
3. The documentation for the Dashboard JSON schema doesn't include `"restricted_roles"`, only `"is_read_only"`.

(2) might be a provider bug? Or it could be some eccentricity in the API response to read a dashboard?

**Comment by skarimo** [comment]
Thanks those are valid points. I checked in with the relevant teams and:

1) This was intentional to ensure a valid UI interaction. However in the case of copying the dashboard from UI to terraform will cause issues issues with restricted roles. For your use case, it would probably be better to retrieve the dashboards using the api and using the output as it will include the restricted_roles. 

2) This is expected so that terraform and API defaults are handled the same. Regardless of the diff shown, the behavior will be the same which is dropping the `restricted_roles` when neither `is_read_only` or `restricted_roles` is set. This is related to: https://github.com/DataDog/terraform-provider-datadog/pull/1854

3) We have reached out to our documentation to update it accordingly. You can use our public api docs which will contain all of the supported attributes: https://docs.datadoghq.com/api/latest/dashboards/#create-a-new-dashboard

Thanks for the feedback, Im going to close this issue but feel free to re-open if needed!
