### ISSUE TITLE
synthetic test import - object contains unparsed element -  map[password: username:]

### ISSUE THREAD

**Issue by Jean-Marc-Le-Fevre** [DataDog/terraform-provider-datadog#2218]
### Datadog Terraform Provider Version

3.34.0

### Terraform Version

1.6.2

### What resources or data sources are affected?

synthetic_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "alfred-synthetic-test-login"{
  locations = ["somewhere"]
  name      = "Name"
  status    = "live"
  type      = "browser"
  request_basicauth  = [
    {
      username = ""
      password = ""
    }]
}
```

### Relevant debug or panic output

│ Error: object contains unparsed element: map[password:****r username:****]

### Expected Behavior

We should be able to import the synthetic test to our state file

### Actual Behavior

Issue while importing (terraform import) and terraformer import

### Steps to Reproduce

* Create a synthetic test in the Datadog UI with basic auth
* do a terraform import

### References

Seems similar to https://github.com/DataDog/terraform-provider-datadog/issues/1335

**Comment by nkzou** [comment]
I wasn't able to reproduce this through the Datadog web app, but I was with the api. I suspect this is occurring because the api doesn't populate the `type` field of the basic auth object. It should look like `{"type":"web","username":"***","password":"***"}`, but from the error message you have, it doesn't have the `type` field.

I'll include a workaround I found for fixing this, even though I wasn't able to reproduce it using your exact steps, through the UI -
go into the datadog web app, clicking "Edit test", and saving the test without making any changes. This should update the model on the backend to properly set `type: web`. 

Let me know if the problem persists.

**Comment by nkzou** [comment]
If the issue persists, please re-open the issue, thanks!
