### ISSUE TITLE
Add support for global_time time_window in service_level_objective_definition widget

### ISSUE THREAD

**Issue by Nordle** [DataDog/terraform-provider-datadog#768]
### Terraform Version
`0.13.3`

### Affected Resource(s)
`datadog_dashboard (2.17.0)`

### Expected Behavior
`Dashboard is imported`

### Actual Behavior
`Error: error getting dashboard: Data failed to match schemas in oneOf(WidgetDefinition):`

### Steps to Reproduce
This is the widget that had to be removed otherwise the above error occurs.
```
widget {
    service_level_objective_definition {
      title             = "SLO"
      title_size        = "16"
      title_align       = "center"
      slo_id            = "12345678987654321"
      time_windows      = ["30d", "7d", "global_time"]
      view_type         = "detail"
      view_mode         = "overall"
      show_error_budget = false
    }
    layout = {
      x      = 19
      y      = 19
      width  = 66
      height = 21
    }
  }
```
Is it possible to add support for this widget?

**Comment by nmuesch** [comment]
Hey @Nordle thanks for the issue report. I was taking a look at this and haven't been able to reproduce with version v2.17.0 of the datadog provider. Currently the dashboard resource does include support for service_level_objective widgets - https://github.com/DataDog/terraform-provider-datadog/blob/v2.17.0/datadog/resource_datadog_dashboard.go#L725

My attempt to reproduce the issue was to:
* Create a new screenbaord in the UI
* Add an SLO widget
* Use `terraform import datadog_dashboard.my_service_dashboard <dash_id>`

However this seems to import successfully for me. Could you share more information about the full reproduction steps and, if possible, a full dashboard trying to be imported (redacting anything potentially sensitive)

**Comment by nmuesch** [comment]
@Nordle looking into this further it looks to be that `global_time` is not currently supported as a valid `time_windows` option in the dashboard resource. This was raised internally to the appropriate team.

**Comment by therve** [comment]
I believe it was fixed in our last release. Let us know if it doesn't work. Thanks!
