### ISSUE TITLE
Upgrade to version 2 of the Terraform Plugin SDK

### ISSUE THREAD

**Issue by kmoe** [DataDog/terraform-provider-datadog#875]
This provider is currently using a legacy version of the Terraform Plugin SDK, v1.15.0. We recommend upgrading to the latest version of the SDK, version 2.

This version offers a number of improvements. Updates to version 1 of the SDK will be made only in exceptional cases.

Please see the [Terraform Plugin SDK v2 Upgrade Guide](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html) for how to upgrade. The [`tf-sdk-migrator v2upgrade`](https://github.com/hashicorp/tf-sdk-migrator#tf-sdk-migrator-v2upgrade-migrate-from-sdkv1-to-sdkv2) command can be used to rewrite import paths.

Feel free to reach out to the @hashicorp/terraform-enablement-sdk team if you need help upgrading.

**Comment by therve** [comment]
Hi,

I believe we're blocked because of our incorrect usage of TypeMap. We started migrating away from those, but we need to create new attributes and deprecate the old ones, but it will take some time.
We're also seeing some performance degradation in tests, which we may need some help troubleshooting.
